In [2]:
import pandas as pd

In [3]:
data=pd.read_csv("general_data.csv")

In [23]:
data.std()


Age                            9.133301
DistanceFromHome               8.105026
Education                      1.023933
EmployeeCount                  0.000000
EmployeeID                  1273.201673
JobLevel                       1.106689
MonthlyIncome              47068.888559
NumCompaniesWorked             2.498887
PercentSalaryHike              3.659108
StandardHours                  0.000000
StockOptionLevel               0.851883
TotalWorkingYears              7.782222
TrainingTimesLastYear          1.288978
YearsAtCompany                 6.125135
YearsSinceLastPromotion        3.221699
YearsWithCurrManager           3.567327
dtype: float64

In [6]:
data.head(5)

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   51        No      Travel_Rarely                   Sales                 6   
1   31       Yes  Travel_Frequently  Research & Development                10   
2   32        No  Travel_Frequently  Research & Development                17   
3   38        No         Non-Travel  Research & Development                 2   
4   32        No      Travel_Rarely  Research & Development                10   

   Education EducationField  EmployeeCount  EmployeeID  Gender  ...  \
0          2  Life Sciences              1           1  Female  ...   
1          1  Life Sciences              1           2  Female  ...   
2          4          Other              1           3    Male  ...   
3          5  Life Sciences              1           4    Male  ...   
4          1        Medical              1           5    Male  ...   

   NumCompaniesWorked Over18 PercentSalaryHike  StandardHours  \
0                 1.0      Y                11              8   
1                 0.0      Y                23              8   
2                 1.0      Y                15              8   
3                 3.0      Y                11              8   
4                 4.0      Y                12              8   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear  YearsAtCompany  \
0                 0               1.0                      6               1   
1                 1               6.0                      3               5   
2                 3               5.0                      2               5   
3                 3              13.0                      5               8   
4                 2               9.0                      2               6   

   YearsSinceLastPromotion  YearsWithCurrManager  
0                        0                     0  
1                        1                     4  
2                        0                     3  
3                        7                     5  
4                        0                     4  

[5 rows x 24 columns]

In [9]:
data.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'Department', 'DistanceFromHome',
       'Education', 'EducationField', 'EmployeeCount', 'EmployeeID', 'Gender',
       'JobLevel', 'JobRole', 'MaritalStatus', 'MonthlyIncome',
       'NumCompaniesWorked', 'Over18', 'PercentSalaryHike', 'StandardHours',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'YearsAtCompany', 'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

In [11]:
data1=data.head(25)

# HYPOTHESIS 1



AVERAGE AGE OF EMPLOYEE IS 36 YEARS


In [59]:
data1.mean()


Age                           36.880000
DistanceFromHome               8.440000
Education                      2.960000
EmployeeCount                  1.000000
EmployeeID                    13.000000
JobLevel                       1.800000
MonthlyIncome              64714.400000
NumCompaniesWorked             1.720000
PercentSalaryHike             14.720000
StandardHours                  8.000000
StockOptionLevel               1.040000
TotalWorkingYears             12.083333
TrainingTimesLastYear          2.920000
YearsAtCompany                 8.480000
YearsSinceLastPromotion        3.120000
YearsWithCurrManager           4.920000
dtype: float64

In [19]:
data1["Age"].std()


9.475054969057787

# #Assume level of significance is 0.05 and number of observations to be 25 and one column
#Hence

In [21]:
z=(36.88-36)/(9/5)
z


0.4888888888888903

In [22]:
print("Table test value: 1.960")



Table test value: 1.960


SINCE calculated z value lies within the range of table test value,It is safe to say the mean age of employees is 36 years.

# HYPOTHESIS 2

The average age of an employee is 42 years.Assume error rate of 0.05 and S is 9 and number of observations is 25

In [27]:
t=(36.88-42)/(9/3)
t

-1.7066666666666659

In [26]:
print("The corresponding table value : 2.064")

The corresponding table value : 2.064


Since calulated t value lies in the range -2.064 to + 2.064, The given statement can be said to be true

# HYPOTHESIS 3

The mean age of employees is less than 15.Assume error rate of 0.05 and S is 9 and number of observations is 25

Given statement is one tail, and in one tail, it is right tail and since S is given, we should consider 1 tail,right tail T test

In [28]:
t=(36.88-15)/(9/5)
t

12.155555555555557

In [29]:
print("The corresponding table value: 1.711")

The corresponding table value: 1.711


Since calculated value of t is lying outside the range (-1.711,+1.711), The given statement is false

# HYPOTHESIS 4

The mean age of employees is greater than 34.Assume error rate of 0.05 and S is 9 and number of observations is 25

In [34]:
t=(36.88-34)/(9/5)
t

1.6000000000000014

In [35]:
print("The corresponding table value: 1.711")

The corresponding table value: 1.711


Since calculated value of t is lying inside  the range (-1.711,+1.711), The given statement is true

# HYPOTHESIS 5

In [36]:
data3=data.tail(36)

In [51]:
data3.std()

Age                            8.288977
DistanceFromHome               9.622889
Education                      1.081959
EmployeeCount                  0.000000
EmployeeID                    10.535654
JobLevel                       0.949520
MonthlyIncome              42673.149567
NumCompaniesWorked             2.711011
PercentSalaryHike              3.637001
StandardHours                  0.000000
StockOptionLevel               0.806226
TotalWorkingYears              7.671512
TrainingTimesLastYear          1.218899
YearsAtCompany                 7.702968
YearsSinceLastPromotion        3.572714
YearsWithCurrManager           3.924283
dtype: float64

In [39]:
data.std()

Age                            9.133301
DistanceFromHome               8.105026
Education                      1.023933
EmployeeCount                  0.000000
EmployeeID                  1273.201673
JobLevel                       1.106689
MonthlyIncome              47068.888559
NumCompaniesWorked             2.498887
PercentSalaryHike              3.659108
StandardHours                  0.000000
StockOptionLevel               0.851883
TotalWorkingYears              7.782222
TrainingTimesLastYear          1.288978
YearsAtCompany                 6.125135
YearsSinceLastPromotion        3.221699
YearsWithCurrManager           3.567327
dtype: float64

The mean of distance from home of employyes is 15. Assume error rate is 0.05 and S=8.10 and n=36 and xbar=10.8

In [43]:
z=(10.8-15)/(8.10/6)
z

-3.1111111111111107

In [45]:
print("The corresponding table value is : 1.960")

The corresponding table value is : 1.960


Since the calculated z value lies outside the range of table value, The given statement is False

# Hypothesis 6

The mean of distance from home of employyes is 12. Assume error rate is 0.05 and S=8.10 and n=36 and xbar=10.8 and n=36

In [44]:
z=(10.8-12)/(8.10/6)
z

-0.8888888888888884

In [46]:
print("The corresponding table value is : 1.960")

The corresponding table value is : 1.960


Since the calculated z value lies inside the range of table value, The given statement is True

# Hypothesis 7

The mean of distance from home of is greater than 10. Assume error rate is 0.05 and S=8.10 and n=36 and xbar=10.8 and n=36

In [48]:
t=(10.8-10)/(8.10/6)
t

0.5925925925925932

In [49]:
print("The corresponding table value is : 1.960")

The corresponding table value is : 1.960


Since the calculated t value lies inside the range of table value, The given statement is True

# Hypothesis 8

The mean of distance from home of is less than 11. Assume error rate is 0.05 and sd=9.61 and n=36 and xbar=10.8 and n=36

In [53]:
z=(10.8-11)/(9.61/6)
z

-0.12486992715920872

In [54]:
print("The corresponding table value is : 1.645")

The corresponding table value is : 1.645


Since the calculated z value lies inside the range of table value, The given statement is True

# Hypothesis 9

The mean of distance from home of equal to 30. Assume error rate is 0.05 and sd=9.61 and n=36 and xbar=10.8 and n=36

In [57]:
z=(10.8-30)/(9.61/6)
z

-11.987513007284079

In [58]:
print("The corresponding table value is : 1.645")

The corresponding table value is : 1.645


Since the calculated z value lies outside the range of table value, The given statement is False

# Hypothesis 10

The monthly income of employees is 65k. Assume error rate is 0.05 and S is 47k and x bar is 64714 and n=25

In [60]:
t=(64714-65000)/(47000/5)
t

-0.030425531914893618

In [61]:
print("The corresponding table value is : 2.060")

The corresponding table value is : 2.060


Since the calculated t value lies inside the range of table value, The given statement is True